---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: accelerator-managed-resources
  namespace: accelerator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: accelerator-managed-resources
rules:
- apiGroups:
  - accelerator.apps.tanzu.vmware.com
  resources:
  - accelerators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - accelerator.apps.tanzu.vmware.com
  resources:
  - accelerators/finalizers
  verbs:
  - update
- apiGroups:
  - accelerator.apps.tanzu.vmware.com
  resources:
  - accelerators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - accelerator.apps.tanzu.vmware.com
  resources:
  - fragments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - accelerator.apps.tanzu.vmware.com
  resources:
  - fragments/finalizers
  verbs:
  - update
- apiGroups:
  - accelerator.apps.tanzu.vmware.com
  resources:
  - fragments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - kappctrl.k14s.io
  resources:
  - apps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: accelerator-managed-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: accelerator-managed-resources
subjects:
- kind: ServiceAccount
  name: accelerator-managed-resources
  namespace: accelerator-system
