apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: samples-misc
spec:
  serviceAccountName: accelerator-managed-resources

  fetch:
  - git:
      url: https://github.com/trisberg/managed-accelerators
      ref: origin/main
      subPath: samples-misc

  template:
  - ytt: {}
  deploy: 
  - kapp: {}
