---
apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: simple
  iconUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/3/35/Information_icon.svg/124px-Information_icon.svg.png?20081119185556"
spec:
  source:
    image: docker.io/trisberg/simple-accelerator
---
apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: my-simple-web-app
  iconUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/3/35/Information_icon.svg/124px-Information_icon.svg.png?20081119185556"
spec:
  git:
    ref:
      branch: main
    url: https://github.com/matt-dres/simple-web-app
